### ISSUE TITLE
Could not resolve placeholder 'info.foo' in string value "${info.foo}"

### ISSUE THREAD

**Issue by gpqhl0071** [ericdahl/spring-cloud-config-example#5]
运行你的代码，提示下面错误，请问什么原因？
Could not resolve placeholder 'info.foo' in string value "${info.foo}"

**Comment by ericdahl** [comment]
I don't speak Chinese 

but, that error would occur from the client if the server is not running, or is not accessible from <http://localhost:8888>. Try re-running the server and then launch the client

**Comment by ramazansakin** [comment]
Could not resolve placeholder 'info.foo' in string value "${info.foo}"
Hi @ericdahl , @gpqhl0071  is right. config server is running and http://localhost:8888/master/development api responds correctly but "Could not resolve placeholder 'info.foo' in string value "${info.foo}"" issue is still going on.
