### ISSUE TITLE
Could not resolve placeholder 'info.foo' in string value "${info.foo}"

### ISSUE THREAD

**Issue by ramazansakin** [ericdahl/spring-cloud-config-example#7]
Could not resolve placeholder 'info.foo' in string value "${info.foo}"
Hi @ericdahl , @gpqhl0071  is right. config server is running and http://localhost:8888/master/development api responds correctly but "Could not resolve placeholder 'info.foo' in string value "${info.foo}"" issue is still going on.

_Originally posted by @ramazansakin in https://github.com/ericdahl/spring-cloud-config-example/issues/5#issuecomment-754007555_

**Comment by ericdahl** [comment]
I can't reproduce this. Can you provide an example of what specifically you are doing to observe that error?

I haven't been working with Java in a couple years. I launched a new VM, installed java and followed the 3 steps from the README here. I don't see any errors.

```
$ curl http://localhost:8080/ ; echo
Using [bar] from config server
```

I'm guessing that you are stopping the server and then running the client. The server needs to be running for the client to connect. This may mean you need to open the client in a second terminal window.

I'll add a note to the README to clarify this
